# Topics Advertised
TrajectoryTopic:            '/example4/trajectory'
WayPointsTopic:             '/example4/waypoints'
RouteTopic:                 '/example4/route'
AccTopic:                   '/example4/acc'

# Frame Name
FrameName:                  'world'

# Params
WeightT:                     1024.0

WeightAcc:                   0.0

WeightJerk:                  1.0

MaxAccRate:                  4.00

MaxVelRate:                  7.00

Iterations:                  23

Epsilon:                     0.02
